### ISSUE TITLE
Cross compile with the full Scala version. (support Scala 2.13.1)

### ISSUE THREAD

**Issue by xuwei-k** [tpolecat/tut#263]
because tut depends on scala compiler.

e.g. tut does not work with Scala 2.13.1

```
[error] (run-main-1) java.lang.NoSuchMethodError: scala.tools.nsc.Settings.usejavacp()Lscala/tools/nsc/settings/AbsSettings$AbsSetting;
```

similar issue https://github.com/typelevel/kind-projector/issues/15

Maybe same issue(?) https://github.com/tpolecat/tut/issues/255

**Comment by alexflav23** [comment]
Any updates here @tpolecat ? Being hit by the same problem currently, oddly only on Travis.

**Comment by tpolecat** [comment]
tut is unmaintained, please switch to mdoc
