### PR TITLE
Test fixes & Scala 2.12

### PR DESCRIPTION
**Pull request by larsrh**
`scripted` now _invokes SBT_ with the correct Scala version (2.10.6) and then uses the user-specified version _inside the tests_.

Travis setup changed such that `scripted` tests are executed for all supported Scala versions.

### CODE REVIEW

**Comment by larsrh** [comment]
@adelbertc For these changes I didn't have to touch anything below `tests/src`, so that shouldn't conflict.

**Comment by tpolecat** [comment]
Can you explain using more words? I don't understand what this is doing. When you say user-specified version where is this specified? The `.sbt` files in the scripted tests are getting it from the environment.

**Comment by tpolecat** [comment]
Also I have been on and off of airplanes for the last 24 hours and am very sleepy.

**Comment by larsrh** [comment]
The problem was the following:

- Travis would call `scripted` with a specific Scala version set, e.g. `sbt ++2.11.8 scripted`. I didn't change that in my previous PR (#125), it was like that before.
- SBT is happy to run that command, although it really shouldn't: `scripted` assumes that the Scala version is identical to SBT's Scala version (2.10.6).
- `tests/build.sbt` then propagated the Scala version it has been happening to be invoked with to the "child" `build.sbt` files in `tests/src/sbt-test`. While this is the correct thing to do, it was done in the wrong way.

What happens now is this:

- Travis calls `scripted` with the correct Scala version, which is 2.10.6 (and also SBT's default).
- Instead of propagating the version it was being run with, `tests/build.sbt` now looks into the environment to figure out what Scala version it should propagate.

**Comment by tpolecat** [comment]
Ok, I guess I'm not sure how that would work. The scripted tests will only work on a fixed version of Scala (2.11) because every version changes the ways errors are formatted, and that's one of the things we're checking for.

**Comment by larsrh** [comment]
> because every version changes the ways errors are formatted, and that's one of the things we're checking for

Right, I just noticed that. I will disable the tests for non-2.11, then. It's still a worthwhile change because my reasoning in the above comment is still true: even for 2.11 the fact that it worked at all is surprising (accidental binary compatibility, to be clear).

**Comment by tpolecat** [comment]
Ok 👍 when it turns green. Thanks!

**Comment by larsrh** [comment]
Also: In case you want to base the tests on 2.12 in the future, this PR makes it possible. It caused `NoSuchMethodError` before.

**Comment by tpolecat** [comment]
Yeah the tests should all get updated to run in 2.12

**Comment by larsrh** [comment]
> Yeah the tests should all get updated to run in 2.12

Should I do it in this PR or in a follow-up?

**Comment by tpolecat** [comment]
Followup is fine. There's no rush. I'll open an issue.
